version: '3.6'
services:
  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
      - 4369:4369
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - db_data:/opt/couchdb/data
      - db_config:/opt/couchdb/etc/local.d

volumes:
  db_data:
  db_config:
